services:
  backend:
    image: telegrammy/backend:voice-call # telegrammy/backend:[module_name] (check with the backend repo)
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    networks:
      my-network:
networks:
  my-network:
