services:
  backend:
    image: telegrammy/backend:group_calls # telegrammy/backend:[module_name] (check with the backend repo)
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    networks:
      my-network:
  redisq:
    image: redis:7.4
    ports:
      - '6379:6379'
    networks:
      my-network:
networks:
  my-network:
